### ISSUE TITLE
Legacy files not written

### ISSUE THREAD

**Issue by tmjoen** [alloc/vite-plugin-legacy#10]
Hi and first of all thanks for a brilliant idea/plugin -- I have removed so much of my old cruddy webpack configs!

I'm having some troubles with the plugin, I can't seem to get it to write the legacy files.

Here is my config:

```es6
import { defineConfig } from 'vite'
import legacyPlugin from 'vite-plugin-legacy'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    legacyPlugin({
      // The browsers that must be supported by your legacy bundle.
      // https://babeljs.io/docs/en/babel-preset-env#targets
      targets: [
        '> 0.5%',
        'last 2 versions',
        'Firefox ESR',
        'not dead',
      ],
      // Define which polyfills your legacy bundle needs. They will be loaded
      // from the Polyfill.io server. See the "Polyfills" section for more info.
      polyfills: [
        'IntersectionObserver',
        // 'CustomEvent', /* not found */
        // 'Element.prototype.append', /* not found */
        // 'HTMLPictureElement', /* not found */
      ],
      // Toggles whether or not browserslist config sources are used.
      // https://babeljs.io/docs/en/babel-preset-env#ignorebrowserslistconfig
      ignoreBrowserslistConfig: false,
      // When true, core-js@3 modules are inlined based on usage.
      // When false, global namespace APIs (eg: Object.entries) are loaded
      // from the Polyfill.io server.
      corejs: true
    })
  ],
  build: {
    manifest: true,
    emptyOutDir: false,
    target: "es2018",
    outDir: "../../priv/static", // <- Phoenix expects our files here
    sourcemap: true, // we want to debug our code in production
    rollupOptions: {
      input: {
        main: "js/index.js",
      }
    },
    terserOptions: {
      mangle: true,
      safari10: true,
      output: {
        comments: false
      },
      compress: {
        pure_funcs: ['console.info', 'console.debug', 'console.warn'],
        global_defs: {
          module: false
        }
      }
    }
  }
})
```

When I run the build command:

```zsh
➜  frontend git:(d43e10e) ✗ yarn build
yarn run v1.22.10
$ vite build
building for production...
../../priv/static/assets/main.131d72bb.js     4.04kb / brotli: 1.56kb
../../priv/static/assets/main.131d72bb.js.map 13.85kb
../../priv/static/assets/vendor.17446dc3.js   139.24kb / brotli: 41.28kb
../../priv/static/assets/vendor.17446dc3.js.map 622.35kb
../../priv/static/assets/main.45414950.css    57.47kb / brotli: 5.20kb
../../priv/static/manifest.json               0.28kb
✨  Done in 4.86s.
```

I also tried simplifying my config with just `plugins: [legacyPlugin()]` but still nothing written. I'm new to Vite so I hope I'm not doing a stupid mistake here, but I can't see it :) 

Thanks for any insight!

**Comment by aleclarson** [comment]
Thanks for the report.

v2.1.0 should work with your project!

**Comment by tmjoen** [comment]
That was fast, thanks!

Indeed, it gets further along in the process now but errors with:

```
building for production...
creating legacy bundle...
error during build:
Error: Could not resolve './vendor.17446dc3.js' from assets/application.8af83337.legacy.js
    at error (/Users/trond/dev/elixir/sites/hp_vite/assets/frontend/node_modules/rollup/dist/shared/rollup.js:5240:30)
    at ModuleLoader.handleResolveId (/Users/trond/dev/elixir/sites/hp_vite/assets/frontend/node_modules/rollup/dist/shared/rollup.js:18638:24)
    at /Users/trond/dev/elixir/sites/hp_vite/assets/frontend/node_modules/rollup/dist/shared/rollup.js:18607:22
    at async Promise.all (index 13)
    at async ModuleLoader.fetchStaticDependencies (/Users/trond/dev/elixir/sites/hp_vite/assets/frontend/node_modules/rollup/dist/shared/rollup.js:18605:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/Users/trond/dev/elixir/sites/hp_vite/assets/frontend/node_modules/rollup/dist/shared/rollup.js:18582:9)
    at async Promise.all (index 0)
error Command failed with exit code 1.
```

This is what my `manifest.json` looks like when building **without** `legacyPlugin`:

```es6
{
  "js/index.js": {
    "file": "assets/main.88bb3872.js",
    "src": "js/index.js",
    "isEntry": true,
    "imports": [
      "_vendor.17446dc3.js"
    ],
    "css": [
      "assets/main.5ba20361.css"
    ]
  },
  "_vendor.17446dc3.js": {
    "file": "assets/vendor.17446dc3.js"
  }
}
```

I can open a new issue if you prefer?

Thanks again!

**Comment by aleclarson** [comment]
Yeah that seems unrelated to this issue.

The problem here was `build.rollupOptions.input` not being supported.
